version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  install-node-example:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "16.13"
      - run: node --version
      - run: git checkout main
      - run: npm install
      - run:
          name: build main baseline
          command: |
            npm run build
      - run: git checkout "$CIRCLE_BRANCH"
      - run: npm install
      - run:
          name: build branch
          command: |
            npm run build
          environment:
            COMPARE: true

workflows:
  build_and_test:
    jobs:
      - install-node-example
