version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  install-node-example:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "18.17.0"
      - run: node --version
      - run: git checkout main
      - run: yarn
      - run:
          name: build main baseline
          command: |
            BUNDLE_STATS_BASELINE=true npm run build
      - run: git checkout "$CIRCLE_BRANCH"
      - run: yarn
      - run:
          name: build branch baseline
          command: |
            npm run build
      - run:
          name: build branch baseline
          command: |
            node ./scripts/size-bot.js

workflows:
  build_and_test:
    jobs:
      - install-node-example
